dominodatalab/terraform-aws-eks

- iam-bootstrap/bootstrap-0.json
- iam-bootstrap/bootstrap-1.json
- iam-bootstrap/iam.tf
- iam-bootstrap/outputs.tf
- iam-bootstrap/render.sh
- iam-bootstrap/variables.tf
- iam-bootstrap/versions.tf
* Policies meant to be deployed and used separate from the main module
* End users / deploy engineers would provision the module (or manually provision the policies), manually assume the role (or use an associated user they've created) and then provision the main EKS module
* The main EKS module doesn't have any interaction with the policy, as it does not need to know about it
* See https://github.com/cerebrotech/platform-apps/pull/6505 for the internal deployer automation for this
> PLAT-3795: Terraform module and IAM policies for deployment

- submodules/eks/node-group.tf
- submodules/eks/templates/gpu_cert_setup.tpl
- submodules/eks/templates/linux_user_data.tpl
Although the regular EKS ami sets up containerd with some cert directories, the GPU EKS ami does not.
This either adds a part before the default user data to set that up when no AMI was specified, or adds the same code to our custom user data for custom AMIs.
> PLAT-6183: Setup containerd certs directory on GPU nodes

- submodules/eks/k8s.tf
- submodules/k8s/README.md
- submodules/k8s/main.tf
- submodules/k8s/templates/k8s-functions.sh.tftpl
- submodules/k8s/variables.tf
SOCKS proxy is incompatible with awscli. This normally doesn't matter the way this module is used, but when a role is specified then awscli needs to call out and fails at the socks proxy.
By moving the proxy config into the kubeconfig, kubectl uses the proxy and awscli doesn't, fixing this issue.
I use `sed` to add the `proxy-url` key rather than `yq`, even though it's dumber, to avoid adding an additional pre-req.
> Set proxy-url in kubeconfig (temporarily)

- submodules/eks/templates/gpu_cert_setup.tpl
They release the fixed GPU ami, however, it was not, in reality, fixed.
See: https://github.com/awslabs/amazon-eks-ami/issues/1154#issuecomment-1414711705
Because the incorrect version of the certs config triggers the safety valve of the old remediation, a new one is needed.
> PLAT-6183: Update gpu ami remediation

- README.md
- main.tf
- submodules/eks/README.md
- submodules/eks/k8s.tf
- submodules/eks/node-group.tf
- submodules/eks/variables.tf
- submodules/k8s/README.md
- submodules/k8s/main.tf
- submodules/k8s/templates/aws-auth.yaml.tftpl
- submodules/k8s/variables.tf
- variables.tf
* Don't recreate node security group just because of name/description
* Allow custom aws-auth map role entries
* Allows us to use original nodegroup iam role so we don't break OG ASGs prior to switchover
* Mainly for peace of mind (Domino isn't suddenly down)
> PLAT-5668: Minor conversion process tweaks

- README.md
- main.tf
- submodules/eks/README.md
- submodules/eks/node-group.tf
aws_default_tags isn't resolved within the module so the launch template version is bumped regardless of whether there was actually a tag change. this then causes the node group to update and all nodes to roll.
> avoid bumping the launch template for no-op changes

- submodules/k8s/README.md
- submodules/k8s/main.tf
- submodules/k8s/templates/k8s-functions.sh.tftpl
- submodules/k8s/variables.tf
Updates the calico manifests as they are being removed from the aws repo,https://github.com/aws/amazon-vpc-cni-k8s/issues/2287
Also needed to support eks 1.25,[PLAT-6342](https://dominodatalab.atlassian.net/browse/PLAT-6342)
> PLAT-6336 Update Calico install manifests.

- submodules/k8s/main.tf
- submodules/k8s/templates/k8s-functions.sh.tftpl
Because we don't trigger re-running the setup script on all script/yaml updates, but still do on the root script, in situations where we make changes in the accompanying files we are basically kicking the can down the road to find all the places we broke upgrade compatibility.
In this case, it seems like we broke upgrade compatibility with calico on the recent calico change.
> Trigger setup script on all component changes

- submodules/eks/README.md
- submodules/eks/node-group.tf
When using a non-EKS AMI, the root device name can be different than `xvda`.
> lookup custom AMI root device name for node groups

- .circleci/config.yml
Static credentials have a tendency to get stale and OIDC was relatively straightforward to setup. I'll remove the static keys from CircleCI once this is merged.
> switch to OIDC for AWS credentials in CI

- submodules/eks/iam.tf
`eks:DescribeNodegroup` is the main one I think we're missing, but the rest are useful if we ever want to use launch templates with min/max resource requirements instead of instance types.
https://github.com/kubernetes/autoscaler/blob/cluster-autoscaler-1.25.0/cluster-autoscaler/cloudprovider/aws/README.md#full-cluster-autoscaler-features-policy-recommended
> add autoscaling IAM policy requirements

- submodules/k8s/templates/k8s-functions.sh.tftpl
As part of [PLAT-6387](https://dominodatalab.atlassian.net/browse/PLAT-6387), we need to set the registry to `quay.io` as we are getting rate limited by `docker.io`.
Setting registry as per [doc](https://docs.tigera.io/calico/latest/reference/installation/api#operator.tigera.io/v1.InstallationSpec).
> PLAT-6387 registry defaults to docker.io, set to quay

- submodules/eks/main.tf
Open inbound ports for APIServices: metrics-server, prometheus-adapter and calico
Remove Control Plane egress rules. The Control Plane SG is added to the nodes which means ingress is all that matters. We are egressing to a set of ENIs that have an EKS managed SG and not the one we believe we are controlling. Everything is working because we allow everything from a node to the internet.
> Adjust node security group rules (APIServices)

- .circleci/config.yml
aws-cli/setup doesn't support `when: always` so the role assume before destroy didn't actually run.
> use a longer duration because aws-cli/setup does not support running on destroy

- examples/tf-plan-test.sh
`examples/tf-plan-test.sh` will be incorporated into CI later as well as testing `bring-your-vpc` .
> Adds a simple sh to run a tf plan on the examples

- submodules/k8s/templates/k8s-functions.sh.tftpl
Might be a me problem, but if the ssh-agent has too many identities it can cause rate-limit auth failures.
> set IdentitiesOnly=yes when SSHing to bastion

- examples/minimal-with-bastion/README.md
- examples/minimal-with-bastion/main.tf
- examples/minimal-with-bastion/variables.tf
- submodules/eks/README.md
- submodules/eks/k8s.tf
- submodules/eks/node-group.tf
- submodules/k8s/README.md
- submodules/k8s/main.tf
- submodules/k8s/outputs.tf
- submodules/k8s/templates/k8s-pre-setup.sh.tftpl
- submodules/k8s/variables.tf
To push Calico install to the end in #71, I referenced the k8s submodule twice. This was intentional, even though it was a bit messy, as we were simply rewriting the same template files, but this apparently is causing issues with s3 as a store.
This takes a hybrid approach, keeping the modularization of the scripts overall, but putting the actual execution into the EKS module.
> Refactor split submodule scripts

- .pre-commit-config.yaml
- submodules/eks/cluster.tf
* [ignore CKV_AWS_339: kubernetes version is specified as a variable](https://github.com/dominodatalab/terraform-aws-eks/commit/4c115cd48c2adb84c43d14b38cc475d9c80cc41b)
* [specify a year-long retention on the EKS cluster logs](https://github.com/dominodatalab/terraform-aws-eks/commit/4d3a584bd2228866948565b8b693e9715d80ac7e)
> Address new checkov errors; kubernetes version and cloudwatch log group retention

- main.tf
[PLAT-6614](https://dominodatalab.atlassian.net/browse/PLAT-6614)
prevent VPC recreation on upgrade from older versions of this module.
> support update from refactored network module

- .pre-commit-config.yaml
- iam-bootstrap/bootstrap-0.json
- iam-bootstrap/bootstrap-1.json
- submodules/storage/efs_backup_vault.tf
Our iam bootstrap glue in the deployer has been broken. :(
Because of this, a small number of more recent requirements since this was created are missing from this role.
A fix to the deployer side of this is forthcoming, but will wait on PLAT-6617 since that will solve a key problem that comes with fixing it. That problem is that once the iam role is the creator, installs become impossible without adding the role to the kubeconfig—something for which there is a chicken/egg problem that will be solved better by PLAT-6617 than what would be done deployer-side. Also means there's one fewer changes in how this fundamentally works.
> PLAT-6671: Iam boostrap updates

- submodules/eks/iam.tf
[PLAT-6849](https://dominodatalab.atlassian.net/browse/PLAT-6849)
Fixes hardcoded `aws` partition.
> PLAT-6849 Fix hardcoded aws partition.

- .github/workflows/terraform-checks.yml
- .pre-commit-config.yaml
- bin/check-aws-partition.sh
Adds a pre-commit hook that checks for hardcoded `aws` partitions, like `arn:aws`. 
The following are the supported partitions:
```
aws - AWS Regions
aws-cn - China Regions
aws-us-gov - AWS GovCloud (US) Regions
```
Also the yaml formatter is partial to `"` over `'`.
pre-commit test:
GHA [job](https://github.com/dominodatalab/terraform-aws-eks/actions/runs/5381532041/jobs/9765724871) test:
> Precommit to check for hardcoded aws partition

- iam-bootstrap/bootstrap-0.json
https://dominodatalab.atlassian.net/browse/DOM-47755
Extension of https://github.com/dominodatalab/terraform-aws-eks/pull/106
The ACM certificate created by the dataplane deployer needs to be validated though Route53.
> DOM-47755 • Dataplane deployment failure

- submodules/eks/k8s.tf
Execute scripts using bash not as a command to bash. This avoids issues with file permissions getting lost along the way.
> PLAT-6938: Run scripts with bash

- main.tf
Because network also depends on storage, any KMS key change will cause the whole module data sources to refresh even though nothing has changed.
Original change was in https://github.com/dominodatalab/terraform-aws-eks/pull/5, but the use-case no longer exists.
> remove coupling between eks and network modules

- iam-bootstrap/bootstrap-0.json
- submodules/eks/node-group.tf
* eks:UpdateNodegroupConfig is used to change nodegroup configuration in-place
* If nodegroup `min_size` is changed, we don't particularly care and can ignore it
> Support UpdateNodegroupConfig in bootstrap IAM, ignore min_size for nodegroup scaling

- submodules/eks/README.md
- submodules/eks/cluster.tf
[DOM-49709](https://dominodatalab.atlassian.net/browse/DOM-49709)
Upon initial install  `aws_eks_addon` computes the default version, but these can be deprecated and the same `aws_eks_addon` will fail to update if the version is not updated as well.
Given the following example where there were updates to the resource definition, and the `v1.11.4-eksbuild.1` had been deprecated:
```
resource "aws_eks_addon" "vpc_cni" {
addon_name        = "vpc-cni"
addon_version     = "v1.11.4-eksbuild.1"
truncated for brevity...
```
Upon update `resolve_conflicts` fields update(Notice the version is not being updated)
```
~ resource "aws_eks_addon" "vpc_cni" {
+ configuration_values        = jsonencode(
{
+ env = {}
}
)
id                          = "se-test26353:vpc-cni"
- resolve_conflicts           = …
```
> Explicitly set the default EKS addon version

- iam-bootstrap/bootstrap-0.json
The `iam_bootstrap` role is missing resource `"arn:${data.aws_partition.current.partition}:iam::${local.aws_account_id}:role/aws-service-role/*"` for action `iam:CreateServiceLinkedRole"` causes the following on a fresh account.
```
Error: creating EKS Node Group (cloud-dogfood:cloud-dogfood-compute-1): InvalidRequestException: Failed to create service linked role: AWSServiceRoleForAmazonEKSNodegroup due to missing permissions for 'iam:CreateServiceLinkedRole'
{
RespMetadata: {
StatusCode: 400,
RequestID: "6c842182-9eca-4c5f-9c82-a4681b7cc680"
},
Message_: "Failed to create service linked role: AWSServiceRoleForAmazonEKSNodegroup due to missing permissions for 'iam:CreateServiceLinkedRole'"
}
```
> Adds the aws-service-role resource to CreateServiceLinkedRole action

- modules/nodes/nodes.tf
Because ASG's are not created by the terraform the default tags are not propagated.  Apparently this was a duplicate issue with instance tags somewhere in the past, because the functionality to bring the default tags down to the nodegroups already exists.  
All this commit does is include this same variable set so that the asg's get tagged as well.
> PLAT-6790 Add instance_tags to the asg's themselves as well

- examples/deploy/tf.sh
Adding the max parallel threads in case of a nodes apply to mitigate node_groups concurrency errors
> Reduce parallelism in case of a nodes apply

- modules/infra/README.md
- modules/infra/submodules/storage/README.md
- modules/infra/submodules/storage/versions.tf
- modules/infra/versions.tf
Registry released `v5.18.1` 
```
Initializing provider plugins...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/aws v5.18.1...
- Installed hashicorp/aws v5.18.1 (signed by HashiCorp
```
> Remove version pin for aws provider

- modules/eks/main.tf
Need to add a special rule to allow the k8s apiserver to connect to the vault agent injector webhook
tested against a dev-v2 that it does what we want!
> [DOM-48979] -- add vault agent webhook port

- modules/infra/submodules/storage/README.md
- modules/infra/submodules/storage/main.tf
- modules/infra/submodules/storage/s3.tf
This is two changes in one:
1. We see (very) occasional timeouts when provisioning new infra: `(xyz-monitoring) ACL: operation error S3: PutBucketAcl, https response error StatusCode: 400`. My hunch is some sort of propagation delay for the ownership control setting.
2. We don't really need to use ACLs and the preference going forward is to just use policies. However, this is complicated because of our existing infrastructure. In order to set the policy to `BucketOwnerEnforced` the existing grants need to be removed. AFAICT for new installs, there's no way to automatically bypass the grant removal.
> convert monitoring bucket away from ACLs

- examples/tfvars/custom-node-pool.tfvars
- modules/nodes/main.tf
[PLAT-7660](https://dominodatalab.atlassian.net/browse/PLAT-7660)
If a `node_group` contains an instance with `itype` gpu or `node_group.gpu : true` add default labels and taints.
> PLAT-7660 Adds default gpu labels/taints

- README.md
Updating docs to reference to latest version for terraform-aws-domino-backup
> [DOM-51690] Pointing to latest domino backup

- modules/eks/main.tf
Per RE-1649 we need an inbound SG rule. There needs to be a firewall rule open between the eks control plane and the deployment nodes for this to work.
This work is being tracked in RE-1733
> RE-1733 add SG rule for NewRelic metadata injector webhook

- modules/iam-bootstrap/bootstrap-1.json
The EFS backup force destroy feature of Terraform is silently failing calls to `DescribeRecoveryPoint` when used under the IAM bootstrap role, which makes it appear to fail as if the force destroy option doesn't work. In reality, it is trying to destroy the recovery points, but it can't track whether or not the destruction happened. It just doesn't appear to error when DescribeRecoveryPoint fails, and instead it just moves on and tries to delete the backup vault before it's ready.
This adds the missing permission to iam bootstrap.
> PLAT-7948: Add DescribeRecoveryPoint to bootstrap

- modules/flyte/iam.tf
We are relying of flyteadmin to generate signed urls that can be used to download data from workflows, so it needs access to the data bucket.
https://dominodatalab.atlassian.net/browse/DOM-55156
> Move flyteadmin from controlplane to dataplane role

- modules/eks/submodules/privatelink/aws-load-balancer-controller_2.5.4_iam_policy.json
- modules/iam-bootstrap/bootstrap-1.json
[PLAT-8298](https://dominodatalab.atlassian.net/browse/PLAT-8298)
During deployment, there can be errors stating the role is ```not authorized to perform: ec2:DescribeAddressesAttribute because no identity-based policy allows the ec2:DescribeAddressesAttribute action```
Add this action to iam-deployment-policies
[PLAT-8298]: https://dominodatalab.atlassian.net/browse/PLAT-8298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PLAT-8298 - Add EC2 DescribeAddressesAttribute

- .github/workflows/terraform-checks.yml
- .pre-commit-config.yaml
- bin/pre-commit/validate-iam-bootstrap.py
- modules/iam-bootstrap/bootstrap-1.json
- modules/iam-bootstrap/bootstrap-2.json
Adding the new ECR rule in #245 put us over the character limit.
Before:
```
$ for i in modules/iam-bootstrap/bootstrap-*.json; do echo -n "$i: " && jq '.' -c "$i" | wc -c; done
modules/iam-bootstrap/bootstrap-0.json: 3338
modules/iam-bootstrap/bootstrap-1.json: 6279
modules/iam-bootstrap/bootstrap-2.json: 948
```
After:
```
$ for i in modules/iam-bootstrap/bootstrap-*.json; do echo -n "$i: " && jq '.' -c "$i" | wc -c; done
modules/iam-bootstrap/bootstrap-0.json: 3338
modules/iam-bootstrap/bootstrap-1.json: 5917
modules/iam-bootstrap/bootstrap-2.json: 1310
```
> move IAM bootstrap rules for ECR to avoid limit

- modules/eks/submodules/k8s/templates/k8s-functions.sh.tftpl
follow-up from #245, tigera-operator has its own specification for the upstream image.
> pull through cache for tigera-operator on quay

- modules/iam-bootstrap/bootstrap-0.json
- modules/iam-bootstrap/bootstrap-1.json
terraform upgrades is failing during upgrades when cloud_billing resources are avaiable due to missing permissions.
update deployment role to include tagging permissions.
> [DOM-58654] - updated tagging permissions

- modules/eks/main.tf
Vcluster's coredns has a target port of 1053, so when using vcluster dns will fail across nodes. This current impacts data plane, and if CI is converted to terraform would be an issue there too.
> PLAT-8786: Add 1053 to node security group for vcluster's coredns

- modules/infra/submodules/storage/netapp.tf
As a result of the fsx filesystem dynamic sizing, terraform tries to reconcile the configuration which causes an error
```
2024-09-10 15:27:06,074 - Error: updating FSx for NetApp ONTAP File System (fs-04a3746d7459eeda4): operation error FSx: UpdateFileSystem, https response error StatusCode: 400, RequestID: d50b73c2-6c70-4afa-9119-d7411595d895, BadRequest: Invalid desired storage capacity provided: 1024 GiB. Desired storage capacity must be at least 10% higher than the existing value of 1331 GiB.
```
This is due to the automatic sizing increasing the capacity and then terraform tries to set it to the configured value.
This change ignores  changes to the `storage_capacity` field which means that we solely rely on the automatic sizing for `storage_capacity` increases.
Also removing …
> Ignore storage_capacity updates

- modules/nodes/nodes.tf
https://dominodatalab.atlassian.net/browse/PLAT-8779
Adds al2023 GPU support
```
aws ec2 describe-images --region us-west-2 --image-ids "$(kubectl get nodes -l dominodatalab.com/node-pool=default-gpu -o json | jq -r '.items[].metadata.labels["eks.amazonaws.com/nodegroup-image"]')"
{
"Images": [
{
"Architecture": "x86_64",
"CreationDate": "2024-09-29T02:26:16.000Z",
"ImageId": "ami-03b91bc878422278e",
"ImageLocation": "amazon/amazon-eks-node-al2023-x86_64-nvidia-560-1.30-v20240928",
"ImageType": "machine",
"Public": true,
"OwnerId": "602401143452",
"PlatformDetails": "Linux/UNIX",
"UsageOperation": "RunInstances",
"State": "available",
"BlockDeviceMappings": [
{
"DeviceName": "/dev/xvda",
"Ebs": {
"DeleteOnTermination": true,
"Iops": 3000,
"SnapshotId": "snap-0f5c615a9e9596469", …
```
> PLAT-8779 AL2023 gpu support

- modules/infra/submodules/bastion/README.md
- modules/infra/submodules/bastion/main.tf
`al2023-ami*` will pick up ECS/Neuron AMIs. It's pretty harmless, but in the interest of consistency.
```
$ aws ec2 describe-images --owners amazon --region us-west-2 --filters Name=name,Values=al2023-ami-* Name=architecture,Values=x86_64 --query 'sort_by(Images, &CreationDate)[0].Name' --page-size 1000
"al2023-ami-ecs-neuron-hvm-2023.0.20230406-kernel-6.1-x86_64"
$ aws ec2 describe-images --owners amazon --region us-west-2 --filters Name=name,Values=al2023-ami-2023* Name=architecture,Values=x86_64 --query 'sort_by(Images, &CreationDate)[0].Name' --page-size 1000
"al2023-ami-2023.5.20240722.0-kernel-6.1-x86_64"
```
I added a commit using SSM parameters if that's simpler: f8d291f.
> only use base AL2023 for bastion

- modules/infra/submodules/storage/netapp.tf
Avoids failure incase the deployid contains `-`
```
Error: creating FSx for NetApp ONTAP Volume (netapp-poc_domino_shared_storage): operation error FSx: CreateVolume, https response error StatusCode: 400, RequestID: 54d9520f-2f83-4cfc-b9b9-9e43b7874cdb, BadRequest: netapp-poc_domino_shared_storage is not a valid volume name. A volume name must begin with a letter or underscore, can only contain alphanumeric characters or "_", and cannot exceed 203 characters in length.
```
> replace - with _ on volume names

- modules/eks/submodules/k8s/templates/k8s-functions.sh.tftpl
[PLAT-8958](https://dominodatalab.atlassian.net/browse/PLAT-8958)
Given the caller script has `set -e` it does not let the helm install retry as the execution is halted.
> PLAT-8958 fix helm install nor retrying

- modules/flyte/README.md
- modules/flyte/iam.tf
- modules/flyte/variables.tf
Importer needs access to flyte buckets for lift-and-shift in 6.0.1 too
> PLAT-8781: Give importer access to flytepropeller

- examples/deploy/set-mod-version.sh
- modules/external-deployments/operator_role_policies.tf
Backport of https://github.com/dominodatalab/terraform-aws-eks/pull/293 (and https://github.com/dominodatalab/terraform-aws-eks/pull/298)
This PR https://github.com/cerebrotech/pham-juno-operator-service/pull/161 changes the clean-up process in a way that requires allowing the operator to be able to list Models and EndpointConfigs rather than only describing them.
> Update external-deployments operator role policies (6.0.1 backport)

- modules/iam-bootstrap/README.md
- modules/iam-bootstrap/main.tf
[PLAT-9026](https://dominodatalab.atlassian.net/browse/PLAT-9026)
```
2024-12-05 00:57:57,961 - Warning: Argument is deprecated
2024-12-05 00:57:57,961 - 
2024-12-05 00:57:57,961 -   with module.iam_bootstrap.aws_iam_role.deployment,
2024-12-05 00:57:57,961 -   on /resources/deployer/deploys/platst71497/iam_bootstrap/terraform/modules/iam_bootstrap/modules/iam-bootstrap/main.tf line 44, in resource "aws_iam_role" "deployment":
2024-12-05 00:57:57,961 -   44:   managed_policy_arns = aws_iam_policy.deployment[*].arn
2024-12-05 00:57:57,961 - 
2024-12-05 00:57:57,961 - The managed_policy_arns argument is deprecated. Use the
2024-12-05 00:57:57,961 - aws_iam_role_policy_attachment resource instead. If Terraform should
2024-12-05 00:57:57,961 - exclusively manage all managed policy attachments …
```
> PLAT-9026 managed_policy_arns deprecated

- modules/infra/submodules/storage/outputs.tf
trimming the `aws_ecr_pull_through_cache_rule` broke the very static definition for the calico registry.
> Fix calico_image_registry trimmed output

- modules/infra/submodules/cost-usage-report/s3.tf
For CIS Compliance all the s3 buckets must have the Deny HTTP Requests policy.
Most of the buckets already have it, so i added it to the only ones that did not have it (cost)
> [DOM-52897] Add deny http policy to s3

- modules/infra/submodules/network/outputs.tf
- modules/infra/submodules/network/vpc.tf
```
plan: 32 to add, 4 to change, 0 to destroy.
╷
│ Error: Invalid index
│
│   on .terraform/modules/infra/modules/infra/submodules/network/vpc.tf line 53, in data "aws_prefix_list" "s3":
│   53:   prefix_list_id = aws_vpc_endpoint.s3[0].prefix_list_id
│     ├────────────────
│     │ aws_vpc_endpoint.s3 is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
```
> Conditionally reference the aws_vpc_endpoint.s3

- .github/workflows/terraform-checks.yml
No idea why this `just` started happening, but fixes:
```
Neither Terraform nor OpenTofu binary could be found. Please either set the "--tf-path" hook configuration argument, or set the "PCT_TFPATH" environment variable, or set the "TERRAGRUNT_TFPATH" environment variable, or install Terraform or OpenTofu globally.
```
> Install terraform in gha tf checks

- modules/iam-bootstrap/bootstrap-2.json
- modules/infra/submodules/cost-usage-report/glue.tf
The costs terraform submodule, with cost reporting on, does not currently work when KMS is disabled.
This fixes that so what can use SSE uses SSE, and what can't is simply not encrypted. If you have an issue with the lack of encryption for those things, you should enable KMS, as those two things simply do not support encryption any other way.
> PLAT-9123: Costs module non-kms mode

- modules/infra/submodules/network/outputs.tf
The `vpc_cidrs` and `pod_cidrs`  being passed through to the outputs which is inaccurate for byo network.
> Fix CIDR outputs for vpc and pod subnets

- examples/tfvars/specify-vpc-cidr.tfvars
- modules/infra/submodules/network/variables.tf
Allows for smaller CIDR ranges avoiding 
```
Plan: 62 to add, 0 to change, 0 to destroy.
╷
│ Error: Invalid value for variable
│
│   on .terraform/modules/infra/modules/infra/main.tf line 67, in module "network":
│   67:   network             = var.network
│     ├────────────────
│     │ var.network.cidrs is object with 2 attributes
│
│ Each of network.cidrs must be a valid CIDR block.
│
│ This was checked by the validation rule at .terraform/modules/infra/modules/infra/submodules/network/variables.tf:80,3-13.
```
> Relax network CIDR validation

- modules/infra/main.tf
- modules/infra/submodules/network/outputs.tf
- modules/infra/submodules/network/vpc.tf
- Fixes conditional on the s3 endpoint(gateway) cidr blocks,which we create on most cases.
- Given that we need the monitoring bucket as part of a dataplane deployment we also need the s3 policy.
> Fix s3_cidr output based on wrong condition

- modules/nodes/main.tf
- modules/nodes/nodes.tf
The ` "dominodatalab.com/domino-node" = true` label on the  the `karpenter_node_group` causes scheduling issues for daemonsets.
> PLAT-9189 do not the karpenter nodegroups with domino-node

- modules/infra/main.tf
cost basic S3 bucket creation is not tied to a non-gov region.
> fix costs toggle

- .circleci/config.yml
- modules/eks/cluster.tf
- modules/eks/removed.tf
- modules/eks/removed.tofu
- modules/infra/iam.tf
- modules/infra/removed.tf
- modules/infra/removed.tofu
- modules/infra/submodules/storage/efs.tf
- modules/infra/submodules/storage/removed.tf
- modules/infra/submodules/storage/removed.tofu
- modules/nodes/addons.tf
- modules/nodes/removed.tf
- modules/nodes/removed.tofu
- modules/single-node/addons.tf
- modules/single-node/removed.tf
- modules/single-node/removed.tofu
- tests/deploy/ci-deploy.sh
Tofu-pilling us: Compatibility issues are really just around the removed blocks that this adjusts, otherwise we're currently cross-compatible. So this PR makes us both compatible, and sets one of our two deploy tests to use OpenTofu so we can validate cross compatibility in the future to keep our options open.
Background for the removed block: https://opentofu.org/docs/intro/migration/terraform-1.9/#removed-block
> PLAT-9141: terraform/tofu-specific versions of `removed` refs

- modules/infra/submodules/storage/netapp.tf
[PLAT-9393](https://dominodatalab.atlassian.net/browse/PLAT-9393)
The FSXn Ontap filesystem relies on the list of azs which is not ordered and elements can shuffle triggering a change on `preferred_subnet_id` which causes a [filesystem replacement](https://app.circleci.com/pipelines/gh/cerebrotech/fc-infra-upgrades/3374/workflows/9366ffb2-836a-4d1d-a7cf-deae4fd15180/jobs/7495/parallel-runs/0/steps/0-105?invite=true#step-105-413267_140)
> FSXn filesystem ignore network changes

- modules/eks/k8s.tf
- modules/eks/main.tf
- modules/irsa/main.tf
* We're assuming a list is initialized in a ternary line meant for when it's not in use
* We're failing over to something unnecessary as well
> PLAT-9443: Add try block around potentially-uninitialized list call

- modules/infra/submodules/network/subnets.tf
- modules/nodes/main.tf
- modules/nodes/nodes.tf
Tested with:
[Infra(subnets) Build](https://app.circleci.com/pipelines/github/dominodatalab/terraform-aws-eks/9892/workflows/77ccda69-258d-4832-b4e6-b40418292ae4/jobs/6898/parallel-runs/0/steps/0-115)
Subnet name is really long
```
+ resource "aws_subnet" "private" {
...
+ availability_zone_id                           = "usw2-az1"
...
+ tags                                           = {
+ "Name"                                = "circleci-6898-private-*********b-abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
+ "kubernetes.io/cluster/circleci-6898" = "shared"
+ "kubernetes.io/role/internal-elb"     = "1"
}
}
```
[Nodes Build](https://app.circleci.com/pipelines/github/dominodatalab/terraform-aws-eks/9892/workflows/77ccda69-258d-4832-b4e6-b40418292ae4/jobs/6898/parallel-runs/0/steps/0- …
> Handle long subnet names

- modules/nodes/main.tf
Workaround for when the subnet name has spaces and causes
> Replace whitespace with _ for eks nodegroup names

- modules/eks/cluster.tf
- modules/nodes/nodes.tf
[PLAT-9466](https://dominodatalab.atlassian.net/browse/PLAT-9466)
```
2025-06-20 20:04:17,888 - 
2025-06-20 20:04:17,888 -   on /resources/deployer/deploys/cloud-coatue/terraform/nodes/modules/nodes/modules/nodes/nodes.tf line 57, in resource "aws_launch_template" "node_groups":
2025-06-20 20:04:17,888 -   57:       condition     = length(setsubtract(each.value.availability_zone_ids, data.aws_ec2_instance_type_offerings.nodes[each.key].locations)) == 0
2025-06-20 20:04:17,888 -     ├────────────────
2025-06-20 20:04:17,889 -     │ data.aws_ec2_instance_type_offerings.nodes is object with 4 attributes
2025-06-20 20:04:17,889 -     │ each.key is "karpenter"
2025-06-20 20:04:17,889 -     │ each.value.availability_zone_ids is list of string with 6 elements
2025-06-20 20:04:17,889 - …
```
> PLAT-9465 Single_nodegroup should not enforce all azs  to contain its instance type

- README.md
Add minimum version for aws-cli(`2.23.6`) which would otherwise result in 
```
validation failed:
module.nodes.terraform_data.node_group_update_strategy["gpu-apatil-fannie-private-us-west-2b"] (local-exec): Unknown parameter in updateConfig: "updateStrategy", must be one of: maxUnavailable, maxUnavailablePercentage
module.nodes.terraform_data.node_group_update_strategy["compute-apatil-fannie-private-us-west-2a"] (local-exec): Unknown parameter in updateConfig: "updateStrategy", must be one of: maxUnavailable, maxUnavailablePercentage
```
```
2.23.6
======
* api-change:``eks``: Adds support for UpdateStrategies in EKS Managed Node Groups.
```
> Note minimum aws cli version

- modules/load-balancers/waf.tf
`waf_log_group_policy` and other waf-related resources should not be created when WAF feature is not enabled
> Check waf.enabled on waf.tf resources
