dominodatalab/terraform-aws-eks

.circleci/config.yml
.pre-commit-config.yaml
README.md
iam.tf
submodules/eks/cluster.tf
tests/README.md
tests/main.tf
tests/variables.tf

verify that the infrastructure can be created and no drift occurs afterward

PLAT-3406: initial CI

---

main.tf
submodules/network/README.md
submodules/network/main.tf
submodules/network/subnets.tf
submodules/network/variables.tf

Adding toggles to the network submodule so it can be leveraged by the openshift terraform module

Miguelhar.plat 5749.ocp support

---

iam.tf
main.tf
submodules/bastion/main.tf
submodules/eks/cluster.tf
submodules/eks/iam.tf
submodules/eks/variables.tf
submodules/storage/s3.tf
variables.tf

Just a few misc. things that needed to change to comfortable import EKS infra created by our CDK app.

PLAT-5668: Compatibility fixes for coming from CDK

---

README.md
submodules/eks/main.tf

Allow nodes to connect to all possible backends, e.g., Postgres, MySQL, etc...

PLAT-6143: Nodes can egress everywhere

---

submodules/bastion/main.tf

[PLAT-6385](https://dominodatalab.atlassian.net/browse/PLAT-6385)

PLAT-6385 transient cloud-init issues

---

main.tf
submodules/k8s/main.tf

[PLAT-6386](https://dominodatalab.atlassian.net/browse/PLAT-6386)

PLAT-6386 Eval var.use_pod_cidr before using var.pod_subnets

---

.circleci/config.yml

Not sure why we did not have that before.

Add deploy_id tag to CI Deploys

---

.circleci/config.yml
.pre-commit-config.yaml
submodules/k8s/main.tf
submodules/k8s/templates/k8s-functions.sh.tftpl
tests/main.tf.json

Install calico using a helm chart
[PLAT-6387](https://dominodatalab.atlassian.net/browse/PLAT-6387)

PLAT-6387 Install calico using helm chart

---

submodules/eks/README.md
submodules/eks/main.tf

fix support for EKS master roles passed in variables

---

README.md
examples/bring-your-vpc/README.md
examples/bring-your-vpc/versions.tf
examples/custom-node-pool/README.md
examples/custom-node-pool/versions.tf
examples/kms/README.md
examples/kms/versions.tf
examples/minimal-with-bastion/README.md
examples/minimal-with-bastion/versions.tf
examples/nodes-custom-ami/README.md
examples/nodes-custom-ami/versions.tf
examples/public-access/README.md
examples/public-access/versions.tf
iam-bootstrap/README.md
iam-bootstrap/versions.tf
submodules/eks/README.md
submodules/eks/versions.tf
tests/main.tf.json
versions.tf

The addition of terraform_data usage means we need to up our version requirement.

update required TF version to 1.4

---

examples/create-kms-key/README.md
examples/create-kms-key/main.tf
examples/create-kms-key/outputs.tf
examples/create-kms-key/variables.tf
examples/create-kms-key/versions.tf
examples/kms/README.md
examples/kms/main.tf
examples/tf-plan-test.sh
main.tf

Same as https://github.com/dominodatalab/terraform-aws-eks/pull/85 but a different way

Test provided kms key

---

.pre-commit-config.yaml
README.md
submodules/bastion/main.tf
submodules/eks/cluster.tf
submodules/eks/node-group.tf
submodules/storage/ecr.tf
submodules/storage/efs.tf
submodules/storage/efs_backup_vault.tf
submodules/storage/s3.tf

[PLAT-6614](https://dominodatalab.atlassian.net/browse/PLAT-6614)
Ignore kms changes to avoid resources destruction.

PLAT-6614 handle kms.enabled

---

.pre-commit-config.yaml
iam-bootstrap/variables.tf
submodules/bastion/variables.tf
submodules/eks/iam.tf
submodules/eks/variables.tf
submodules/network/variables.tf
variables.tf

Merging fix to main [PLAT-6697](https://dominodatalab.atlassian.net/browse/PLAT-6697)

Miguelhar.plat 6697.hotfix merge

---

.pre-commit-config.yaml
README.md
submodules/bastion/README.md
submodules/bastion/main.tf
submodules/bastion/versions.tf
submodules/eks/cluster.tf
submodules/network/README.md
submodules/network/nat-gateway.tf
submodules/network/versions.tf
versions.tf

[PLAT-6723](https://dominodatalab.atlassian.net/browse/PLAT-6723)

Update aws v5 deprecated params

---

submodules/storage/README.md
submodules/storage/efs_backup_vault.tf

IAM oversight that went under the radar. Backup vault provisions, but isn't actually working correctly due to this.

PLAT-6711: Attach default backup policy

---

iam-bootstrap/bootstrap-0.json

Additional IAM bootstrap changes for the recent eks creation role and oidc changes

PLAT-6671: STS+OIDC perms for iam bootstrap

---

README.md
iam-bootstrap/bootstrap-0.json
iam.tf
versions.tf

[PLAT-6776](https://dominodatalab.atlassian.net/browse/PLAT-6776)
- Adds `backup:DeleteRecoveryPoint` perms
- Increment delay for `create_eks_role` assume(short term fix). Right fix is to have an intermediate step to ensure the role can be assumed. Will create follow up story

PLAT-6776 Adds RP delete perms

---

iam-bootstrap/variables.tf
iam.tf
submodules/bastion/variables.tf
submodules/eks/variables.tf
submodules/network/variables.tf
variables.tf

[PLAT-7025](https://dominodatalab.atlassian.net/browse/PLAT-7025)

PLAT-7025 Add CreateServiceLinkedRole perms to create-eks-role. Needed for fresh accounts.

---

bin/state-migration/migrate-states.sh
examples/deploy/README.md
examples/deploy/tf.sh
modules/eks/submodules/k8s/main.tf
modules/eks/submodules/k8s/templates/k8s-functions.sh.tftpl
tests/deploy/ci-deploy.sh

* Fixes :
```
2023-08-23 20:14:21,847 -     │ local_file.templates is object with no attributes
2023-08-23 20:14:21,847 -
2023-08-23 20:14:21,847 - The given key does not identify an element in this collection value.
2023-08-23 20:14:21,847 -
2023-08-23 20:14:21,847 - Error: Invalid index
72, in locals:
2023-08-23 20:14:21,847 -   72:   change_hash = "${join("-", [for file in ["k8s_presetup", "k8s_functions_sh", "aws_auth"] : md5(local_file.templates[file].content)])}-${try(md5(local_file.templates["eni_config"].content), "none")}"
```
* `./tf.sh <command> <component>`  -->  `./tf.sh <component> <command>`

Miguelhar.mod fixes

---

modules/eks/submodules/k8s/templates/k8s-functions.sh.tftpl
modules/eks/submodules/k8s/templates/k8s-pre-setup.sh.tftpl

[PLAT-7275](https://dominodatalab.atlassian.net/browse/PLAT-7275)
* Sometimes the executor does not have perms to chmod the private key(`/root/pvt-key.pem`).
* Adds a retry on open ssh tunnel.

PLAT-7275 Fallback fixes

---

examples/deploy/terraform/infra/README.md
examples/deploy/terraform/infra/outputs.tf

[PLAT-7140](https://dominodatalab.atlassian.net/browse/PLAT-7140)
Changes supporting public docs.

PLAT-7140: Adds ssh_bastion_command output to infra.

---

examples/deploy/terraform/infra/outputs.tf

Add `external_docker_registry`(ECR) for `domino_config_values` output

doc add ECR

---

.pre-commit-config.yaml
modules/iam-bootstrap/bootstrap-1.json

[DOM-50553](https://dominodatalab.atlassian.net/browse/DOM-50553)
Adds `kms:UntagResource`

DOM-50553 adds kms:UntagResource

---

modules/iam-bootstrap/bootstrap-1.json

[DOM-50570](https://dominodatalab.atlassian.net/browse/DOM-50570)

DOM-50570 adds ecr:UntagResource

---

modules/eks/submodules/k8s/templates/k8s-functions.sh.tftpl

[PLAT-7380](https://dominodatalab.atlassian.net/browse/PLAT-7380)
- Adds retry to helm cmd.

PLAT-7380 Retry on helm cmd fail

---

examples/tfvars/single-node.tfvars
tests/deploy/single-node/single-node.tfvars

Update ami prefix for dev_v2 image

Update prefix for image ami

---

modules/eks/outputs.tf
modules/eks/submodules/privatelink/outputs.tf
modules/infra/submodules/network/outputs.tf

[PLAT-7535](https://dominodatalab.atlassian.net/browse/PLAT-7535)
- Adds network eips, eks private_link nlbs outputs

Add eip, elb outputs

---

modules/eks/submodules/privatelink/vpc-endpoint-services.tf

Each target group binding requires a individual target group
**Note:** Name cannot be longer than 32 characters.
This fix is required to v66 so adding the same commit to a new tag based on v3.0.14 which is the version used by v66, new tag is [v3.0.14-FixTargetGroup](https://github.com/dominodatalab/terraform-aws-eks/releases/tag/v3.0.14-FixTargetGroup)
https://github.com/dominodatalab/terraform-aws-eks/compare/v3.0.14...v3.0.14-FixTargetGroup
**Why this change?**
before this we were using one single target group for 2 ports, which was “working” because we were lucky, there is a check that runs concurrently to check if each target group binding uses a different ARN in our last deployment that failed

[DOM-53042] Provide single target group for each service and port

---

modules/infra/submodules/bastion/README.md
modules/infra/submodules/bastion/main.tf
modules/infra/submodules/storage/README.md
modules/infra/submodules/storage/efs_backup_vault.tf
tests/deploy/infra-ci.tfvars.tftpl

[PLAT-7815](https://dominodatalab.atlassian.net/browse/PLAT-7815)
Sporadic failures due to IAM propagation of the bastion iam instance and the efs backup role.

PLAT-7815 Wait for bastion instance profile, Check efs backup role

---

modules/eks/cluster.tf
modules/eks/submodules/k8s/templates/k8s-functions.sh.tftpl

[PLAT-7889](https://dominodatalab.atlassian.net/browse/PLAT-7889)

PLAT-7889 move config to vpc-cni install

---

modules/flyte/README.md
modules/flyte/iam.tf
modules/flyte/variables.tf

https://dominodatalab.atlassian.net/browse/DOM-54326

[DOM-54326] Add namespace to flyte terraform

---

modules/iam-bootstrap/bootstrap-0.json

This is probably exceedingly rare, but I did run into it.

add iam:UpdateOpenIDConnectProviderThumbprint to IAM permissions

---

modules/infra/submodules/storage/README.md
modules/infra/submodules/storage/s3.tf

remove long term storage lifecycle
[DOM-55609](https://dominodatalab.atlassian.net/browse/DOM-55609)

[DOM-55609] - removed long term storage lifecycle

---

modules/flyte/README.md
modules/flyte/iam.tf
modules/flyte/variables.tf

Importer needs to be able to lift-and-shift blobs to the flyte buckets

PLAT-8781: Give importer access to flytepropeller

---

modules/infra/submodules/storage/netapp.tf

[PLAT-8957](https://dominodatalab.atlassian.net/browse/PLAT-8957)
Adds missing fsx volume backup tags.

PLAT-8957 Add fsx volume backup tags.

---

modules/infra/submodules/storage/README.md
modules/infra/submodules/storage/netapp.tf
modules/infra/submodules/storage/versions.tf

[PLAT-8971](https://dominodatalab.atlassian.net/browse/PLAT-8971)
There are sporadic instances where the secrets are not being deleted. This change is to ensure they are deleted

ensure secrets are deleted

---

examples/deploy/set-mod-version.sh

Add support for vX.Y.Z-A versions

---

modules/capacity-reservation/README.md
modules/capacity-reservation/main.tf
modules/capacity-reservation/outputs.tf
modules/capacity-reservation/variables.tf
modules/capacity-reservation/versions.tf

Adds `modules/capacity-reservation`, used for [PLAT-8864](https://dominodatalab.atlassian.net/browse/PLAT-8864)

Miguelhar.ocr

---

modules/flyte/README.md
modules/flyte/iam.tf
modules/flyte/variables.tf

Reverts dominodatalab/terraform-aws-eks#276

Revert "PLAT-8781: Give importer access to flytepropeller"

---

examples/deploy/terraform/infra/outputs.tf

Missed example deploy outputs conditional to account for limited storage provisioning

Fix deploy example output to account for no storage

---

examples/tfvars/bring-your-vpc.tfvars
examples/tfvars/cost-usage-report.tfvars
examples/tfvars/custom-node-pool.tfvars
examples/tfvars/dataplane.tfvars
examples/tfvars/ecr_endpoint.tfvars
examples/tfvars/external-deployments.tfvars
examples/tfvars/fips-on.tfvars
examples/tfvars/identity-providers.tfvars
examples/tfvars/kms-add-policies.tfvars
examples/tfvars/kms-byok.tfvars
examples/tfvars/minimal-with-bastion.tfvars
examples/tfvars/minimal-wo-bastion.tfvars
examples/tfvars/netapp.tfvars
examples/tfvars/nodes-custom-ami.tfvars
examples/tfvars/only-efs-storage.tfvars
examples/tfvars/private-link.tfvars
examples/tfvars/public-access.tfvars
examples/tfvars/single-node.tfvars
examples/tfvars/specify-vpc-cidr.tfvars
examples/tfvars/vpn.tfvars
tests/deploy/infra-ci.tfvars.tftpl

Minor description update for tfvars, Update dataplane to use the default ngs

Update examples tfvars

---

modules/infra/submodules/cost-usage-report/s3.tf

[PLAT-9217](https://dominodatalab.atlassian.net/browse/PLAT-9217)

PLAT-9217 adds empty filter

---

.github/CODEOWNERS
examples/karpenter/templates/ec2nodeclasses/domino-eks-compute.yaml
examples/karpenter/templates/ec2nodeclasses/domino-eks-gpu.yaml
examples/karpenter/templates/ec2nodeclasses/domino-eks-neuron.yaml
examples/karpenter/templates/nodepools/compute.yaml
examples/karpenter/templates/nodepools/gpu.yaml
examples/karpenter/templates/nodepools/neuron.yaml
examples/karpenter/templates/nodepools/platform.yaml

[PLAT-9369](https://dominodatalab.atlassian.net/browse/PLAT-9369)
Updates several nodepool defaults.

PLAT-9369 Add Neuron taints as well as update with default values

---

modules/nodes/nodes.tf

Trim node_group_name to 64 chars

---

modules/load-balancers/ddos.tf

2025-07-14 18:31:41,845 - Error: creating Route53 Record: operation error Route 53: ChangeResourceRecordSets, https response error StatusCode: 400, RequestID: 4bade292-8686-4ad4-afad-c339825e97ab, InvalidChangeBatch: [RRSet with DNS name apps-cloud-staging.domino.tech. is not permitted in zone cloud-staging.domino.tech.]

Fixing dns
